seed: 42
# L = LEFT, R = RIGHT, + = JUMP & RIGHT, - = JUMP & LEFT, / = FREEZE (do nothing)
solution: "LR+-/"
minGenomeLength: 30
maxGenomeLength: 50
maxGeneration: 250
populationSize: 100

# ELITISM , ROULETTE , TOURNAMENT
selectionStrategy: "TOURNAMENT"
tournamentSize: 4

# PARENTS , CHILDREN , BOTH
mutationTargetStrategy: "CHILDREN"
mutationRate: 0.3
bitFlipRate: 0.7
bitAddRate: 0.2
bitRemoveRate: 0.1

# ONE_POINT , TWO_POINT , UNIFORM
crossoverStrategy: "UNIFORM"
crossoverRate: 0.9

# KEEP_ALL_OR_NOTHING_RANDOMLY , KEEP_ONE_OR_NOT_RANDOMLY , KEEP_ONLY_FROM_FITTEST_PARENT
crossoverLeftoverStrategy: "KEEP_ONE_OR_NOT_RANDOMLY"

# LINEAR, EXPONENTIAL
lengthPunishingStrategy: "EXPONENTIAL"
lengthPunishingFactor: 0.5

maxSolutions: 15
